language: ruby
rvm:
  - 2.6.3
before_script:
  - bundle exec rake db:create --all
  - bundle exec rake db:migrate
script:
  - RAILS_ENV=test bundle exec rails webpacker:compile
  - bundle exec rake ci:tests
services:
  - postgresql
notifications:
  email: false
