language: ruby
rvm:
  - 2.6.3
before_script:
  - bundle exec rake db:create --all
  - bundle exec rake db:migrate
script:
  - bundle exec rake ci:tests
  - ./bin/webpack
services:
  - postgresql
notifications:
  email: false
